server:
  port: 9003
spring:
#  mvc:
#    view:
#      prefix: /WEB-INF/1231231
#      suffix: .jsp
  devtools:
    livereload:
      enabled: true
      
#mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bitcamp?serverTimeZone=Asia/Seoul
    username: angel
    password: 1234
    
#mybatis
mybatis:
  type-aliases-package: data.mapper,data.dto
  mapper-locations:
  - /mapper/**/*.xml
